# Server
server.port=8080

# MySQL database connection
# Please create database first:
# CREATE DATABASE todolist_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
spring.datasource.url=jdbc:mysql://localhost:3306/todolist_db?useSSL=false&serverTimezone=Asia/Tokyo&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=123456

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JSON date format
spring.jackson.time-zone=Asia/Tokyo
